name: Linux RDP via Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Install xfce4 and xrdp
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp wget
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set password for user
      run: echo 'ubuntu:cyb3rking' | sudo chpasswd

    - name: Add user to xrdp group
      run: sudo adduser ubuntu xrdp

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
        tar -xvzf ngrok.tgz
        sudo mv ngrok /usr/local/bin/ngrok
        chmod +x /usr/local/bin/ngrok

    - name: Auth with ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN

    - name: Start ngrok TCP tunnel
      run: |
        nohup ngrok tcp 3389 > ngrok.log &
        sleep 15
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
        cat tunnels.json

    - name: Extract RDP address
      run: |
        RDP_ADDR=$(cat tunnels.json | grep -oP '(?<=tcp://)[^"]+')
        echo "========================================="
        echo "✅ RDP Info:"
        echo "IP:PORT => $RDP_ADDR"
        echo "Username => ubuntu"
        echo "Password => cyb3rking"
        echo "========================================="

    - name: Keep session alive
      run: |
        for ((i=0; i<360; i++)); do
          echo ">> Session alive for $i minutes"
          sleep 60
        done
